### ISSUE TITLE
Album covers/Artists Pics

### ISSUE THREAD

**Issue by jumiknight** [ubuntufag/classic.fm#1]
Don't know if intentional, but all the albums covers and artists pics are missing.
And it's not just on my profile: http://puu.sh/jOWf5/378ff44210.png

Currently using latest Firefox version and Stylish.

**Comment by CamilleScholtz** [comment]
This is probably party last.fm's fault (See https://sr.ht/8Ogx.png). And I think we are gonna change the pics to text anyways, since what I dislike most about the new interface is the xbox huge pictures for everything.
